name: Publish to VS Code Marketplace

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'package.json'

permissions:
  contents: write

jobs:
  publish-to-marketplace:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
      - name: Bump minor version (second number)
        id: new_version
        run: |
          CURRENT=${{ steps.current_version.outputs.version }}
          MAJOR=$(echo $CURRENT | cut -d. -f1)
          MINOR=$(echo $CURRENT | cut -d. -f2)
          PATCH=$(echo $CURRENT | cut -d. -f3)
          NEWMINOR=$((MINOR + 1))
          NEWVERSION="$MAJOR.$NEWMINOR.0"
          echo "version=$NEWVERSION" >> $GITHUB_OUTPUT
          
      - name: Update package.json version
        run: |
          npm version ${{ steps.new_version.outputs.version }} --no-git-tag-version
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add package.json
          git commit -m "Bump minor version to ${{ steps.new_version.outputs.version }} for marketplace release [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push
      
      - name: Delete package-lock.json and install dependencies
        run: |
          rm -f package-lock.json
          npm install --no-package-lock --ignore-scripts
        
      - name: Compile extension
        run: npm run compile
        
      - name: Package extension
        run: |
          npm install -g @vscode/vsce
          vsce package
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v${{ steps.new_version.outputs.version }}
          release_name: Release v${{ steps.new_version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            New version released to VS Code Marketplace.
            Version: ${{ steps.new_version.outputs.version }}
      
      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yolo-labeling-vs-${{ steps.new_version.outputs.version }}.vsix
          asset_name: yolo-labeling-vs-${{ steps.new_version.outputs.version }}.vsix
          asset_content_type: application/octet-stream
      
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com 